import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class DcService {
  public DC_LIST = [
    {
      Dc_UID: 'DC_112',
      DcName: 'vijaya Diagnostics',
      Grade: 'Grade A',
      Block: true,
      Address: 'DC street, DC colony Ahmedabad',
      Location: 'Techno Park',
      City: 'Chennai',
      state: 'Tamil Nadu',
      Pincode: '600233',
      ContactPerson1Name: 'user 1',
      ContactPerson1No: '1234567892',
      ContactPerson2Name: 'user 2',
      ContactPerson2No: '1234567892',
      Landline: '044-23456798',
      Email: 'user@mail.com',
      Spoc_Name: 'spoc name',
      MER: 'Yes',
      X_RAY: 'Yes',
      ECG: 'Yes',
      TwoD_ECHO: 'Yes',
      Urine_Cotinine: 'Yes',
      CTMT: 'No',
      USG: 'OS',
      Female_Tech: 'OS',
      ReportsTat: 'No',
      HomeVisit: 'No',
      DCVisit: 'Yes',
      TATA_AIG: 'Yes',
      HDFC: 'No',
      SBI: 'No',
      BankName: 'viajaya bank',
      AccHolderName: 'user1',
      AccountNo: '1231154444444',
      BranchAddress: 'Gandhi street, R k nagar',
      IfscCode: 'IFSC00011',
      PanName: 'ALGTSRTYU',
      Mou: null,
      CreditPeriod: '1 week',
      BankDetails: null,
      Tariff: null,
      TariffPrice: '1123.34',
      Pis: null,
      RegistrationCertificate: null,
      Photos: [],
      DCGrading: null,
      DCAudit: null,
      otherDocs: null,
      Remarks: 'Registered a new DC',
    },
    {
      Dc_UID: 'DC_113',
      DcName: 'Sai Diagnostics',
      Grade: 'Grade B',
      Block: true,
      Address: 'DC street, DC colony Ahmedabad',
      Location: 'Techno Park',
      City: 'Chennai',
      state: 'Tamil Nadu',
      Pincode: '600233',
      ContactPerson1Name: 'user 2',
      ContactPerson1No: '1234567892',
      ContactPerson2Name: 'user 2',
      ContactPerson2No: '1234567892',
      Landline: '044-23456798',
      Email: 'user@mail.com',
      Spoc_Name: 'spoc name',
      MER: 'Yes',
      X_RAY: 'Yes',
      ECG: 'Yes',
      TwoD_ECHO: 'Yes',
      Urine_Cotinine: 'Yes',
      CTMT: 'No',
      USG: 'OS',
      Female_Tech: 'OS',
      ReportsTat: 'No',
      HomeVisit: 'Yes',
      DCVisit: 'No',
      TATA_AIG: 'Yes',
      HDFC: 'No',
      SBI: 'No',
      BankName: 'viajaya bank',
      AccHolderName: 'user1',
      AccountNo: '1231154444444',
      BranchAddress: 'Gandhi street, R k nagar',
      IfscCode: 'IFSC00011',
      PanName: 'ALGTSRTYU',
      Mou: null,
      CreditPeriod: '1 week',
      BankDetails: null,
      Tariff: null,
      TariffPrice: '1123.34',
      Pis: null,
      RegistrationCertificate: null,
      Photos: [],
      DCGrading: null,
      DCAudit: null,
      otherDocs: null,
      Remarks: 'Registered a new DC',
    },
    {
      Dc_UID: 'DC_114',
      DcName: 'DK Diagnostics',
      Grade: 'Grade D',
      Block: true,
      Address: 'DC street, DC colony Ahmedabad',
      Location: 'Techno Park',
      City: 'Chennai',
      state: 'Tamil Nadu',
      Pincode: '600233',
      ContactPerson1Name: 'user 2',
      ContactPerson1No: '1234567892',
      ContactPerson2Name: 'user 2',
      ContactPerson2No: '1234567892',
      Landline: '044-23456798',
      Email: 'user@mail.com',
      Spoc_Name: 'spoc name',
      MER: 'Yes',
      X_RAY: 'Yes',
      ECG: 'Yes',
      TwoD_ECHO: 'Yes',
      Urine_Cotinine: 'Yes',
      CTMT: 'No',
      USG: 'OS',
      Female_Tech: 'OS',
      ReportsTat: 'No',
      HomeVisit: 'Yes',
      DCVisit: 'No',
      TATA_AIG: 'Yes',
      HDFC: 'No',
      SBI: 'No',
      BankName: 'viajaya bank',
      AccHolderName: 'user1',
      AccountNo: '1231154444444',
      BranchAddress: 'Gandhi street, R k nagar',
      IfscCode: 'IFSC00011',
      PanName: 'ALGTSRTYU',
      Mou: null,
      CreditPeriod: '1 week',
      BankDetails: null,
      Tariff: null,
      TariffPrice: '1123.34',
      Pis: null,
      RegistrationCertificate: null,
      Photos: [],
      DCGrading: null,
      DCAudit: null,
      otherDocs: null,
      Remarks: 'Registered a new DC',
    },
  ];
  public options = ['Yes', 'No', 'OS'];
  constructor() {}
  public getDcList(): Observable<any> {
    return of(this.DC_LIST);
  }
  public getOptions(): Observable<any> {
    return of(this.options);
  }
}
