import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable, of } from 'rxjs';
import { DC } from '../modal/dc';

@Injectable({
  providedIn: 'root',
})
export class DcService {
  public currentDC: BehaviorSubject<DC>;
  public DC_LIST = [
    {
      Dc_UID: 'DC112',
      DcName: 'vijaya Diagnostics',
      DateOfRegistration: '2023/12/10',
      Grade: 'Premium',
      Block: true,
      Address: 'DC street, DC colony Ahmedabad',
      Location: 'Techno Park',
      City: 'kozhikode',
      State: 'Kerala',
      Pincode: '600233',
      ContactPerson1Name: 'user 1',
      ContactPerson1No: '1234567892',
      ContactPerson2Name: 'user 2',
      ContactPerson2No: '1234567892',
      Landline: '044-23456798',
      Email: 'user@mail.com',
      Spoc_Name: 'spoc name',
      MER: 'Yes',
      X_RAY: 'Yes',
      Lab: 'Yes',
      ECG: 'Yes',
      TwoD_ECHO: 'Yes',
      Urine_Cotinine: 'Yes',
      CTMT: 'No',
      USG: 'OS',
      Female_Tech: 'OS',
      ReportsTat: 'No',
      HomeVisit: 'No',
      DCVisit: 'Yes',
      TATA_AIG: 'Yes',
      HDFC: 'No',
      SBI: 'No',
      BankName: 'viajaya bank',
      AccHolderName: 'user1',
      AccountNo: '1231154444444',
      BranchAddress: 'Gandhi street, R k nagar',
      IfscCode: 'IFSC00011',
      PanNo: 'ALGTSRTYU',
      PanName: 'user',
      Mou: null,
      CreditPeriod: '1 week',
      BankDetails: null,
      Tariff: null,
      TariffPrice: '2223.34',
      Pis: null,
      RegistrationCertificate: null,
      Photos: null,
      DCGrading: null,
      DCAudit: null,
      otherDocs: null,
      Remarks: 'Registered a new DC',
    },
    {
      Dc_UID: 'DC113',
      DcName: 'Sai Diagnostics',
      DateOfRegistration: '2023/11/10',

      Grade: 'Premium',
      Block: true,
      Address: 'DC street, DC colony Ahmedabad',
      Location: 'Techno Park',
      City: 'kozhikode',
      State: 'Kerala',
      Pincode: '600233',
      ContactPerson1Name: 'user 2',
      ContactPerson1No: '1234567892',
      ContactPerson2Name: 'user 2',
      ContactPerson2No: '1234567892',
      Landline: '044-23456798',
      Email: 'user@mail.com',
      Spoc_Name: 'spoc name',
      MER: 'Yes',
      X_RAY: 'Yes',
      Lab: 'Yes',
      ECG: 'Yes',
      TwoD_ECHO: 'Yes',
      Urine_Cotinine: 'Yes',
      CTMT: 'No',
      USG: 'OS',
      Female_Tech: 'OS',
      ReportsTat: 'No',
      HomeVisit: 'Yes',
      DCVisit: 'No',
      TATA_AIG: 'Yes',
      HDFC: 'No',
      SBI: 'No',
      BankName: 'viajaya bank',
      AccHolderName: 'user1',
      AccountNo: '1231154444444',
      BranchAddress: 'Gandhi street, R k nagar',
      IfscCode: 'IFSC00011',
      PanNo: 'ALGTSRTYU',
      PanName: 'user',
      Mou: null,
      CreditPeriod: '1 week',
      BankDetails: null,
      Tariff: null,
      TariffPrice: '3333.34',
      Pis: null,
      RegistrationCertificate: null,
      Photos: null,
      DCGrading: null,
      DCAudit: null,
      otherDocs: null,
      Remarks: 'Registered a new DC',
    },
    {
      Dc_UID: 'DC114',
      DcName: 'DK Diagnostics',
      DateOfRegistration: '2023/11/11',
      Grade: 'Premium',
      Block: false,
      Address: 'DC street, DC colony Ahmedabad',
      Location: 'Techno Park',
      City: 'kozhikode',
      State: 'Kerala',
      Pincode: '600233',
      ContactPerson1Name: 'user 2',
      ContactPerson1No: '1234567892',
      ContactPerson2Name: 'user 2',
      ContactPerson2No: '1234567892',
      Landline: '044-23456798',
      Email: 'user@mail.com',
      Spoc_Name: 'spoc name',
      MER: 'Yes',
      X_RAY: 'Yes',
      Lab: 'Yes',
      ECG: 'Yes',
      TwoD_ECHO: 'Yes',
      Urine_Cotinine: 'Yes',
      CTMT: 'No',
      USG: 'OS',
      Female_Tech: 'OS',
      ReportsTat: 'No',
      HomeVisit: 'Yes',
      DCVisit: 'No',
      TATA_AIG: 'Yes',
      HDFC: 'No',
      SBI: 'No',
      BankName: 'viajaya bank',
      AccHolderName: 'user1',
      AccountNo: '1231154444444',
      BranchAddress: 'Gandhi street, R k nagar',
      IfscCode: 'IFSC00011',
      PanNo: 'ALGTSRTYU',
      PanName: 'user',
      Mou: null,
      CreditPeriod: '1 week',
      BankDetails: null,
      Tariff: null,
      TariffPrice: '1111.34',
      Pis: null,
      RegistrationCertificate: null,
      Photos: null,
      DCGrading: null,
      DCAudit: null,
      otherDocs: null,
      Remarks: 'Registered a new DC',
    },
  ];
  public options = ['Yes', 'No', 'OS'];
  constructor() {
    this.currentDC = new BehaviorSubject<DC>(new DC());
  }
  public getDcList(): Observable<any> {
    return of(this.DC_LIST);
  }
  public getOptions(): Observable<any> {
    return of(this.options);
  }
}
